services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ptmsql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - expensetracker_db:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - expensetracker-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '$MSSQL_SA_PASSWORD' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 45s
      timeout: 5s
    restart: unless-stopped

  migration:
    build:
      context: .
      dockerfile: Dockerfile.datamigration
    container_name: Expense_tracker_Migration
    environment:
      SqlServer__Host: db
      SqlServer__Database: expense_tracker_db
      SqlServer__User: sa
      SqlServer__Password: ${MSSQL_SA_PASSWORD}
      SqlServer__TrustServerCertificate: "true"
    networks:
      - expensetracker-net
    depends_on:
      db:
        condition: service_healthy
    restart: "no"  # usually migrations run once, no restart

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Expense_tracker
    ports:
      - "8020:80"
    environment:
      SqlServer__Host: db
      SqlServer__Database: expense_tracker_db
      SqlServer__User: sa
      SqlServer__Password: ${MSSQL_SA_PASSWORD}
      SqlServer__TrustServerCertificate: "true"
    networks:
      - expensetracker-net
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  expensetracker_db:
networks:
  expensetracker-net:
    driver: bridge
